# Generated by Django 5.1.5 on 2025-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키')),
                ('name', models.CharField(max_length=100, verbose_name='고객명')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('region_level1', models.CharField(blank=True, max_length=50, null=True, verbose_name='광역시/도')),
                ('region_level2', models.CharField(blank=True, max_length=50, null=True, verbose_name='시/군/구')),
                ('region_level3', models.CharField(blank=True, max_length=50, null=True, verbose_name='읍/면/동')),
                ('detailed_address', models.CharField(max_length=100, verbose_name='상세 주소')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('visit_schedule', models.DateTimeField(blank=True, null=True, verbose_name='방문 예정일')),
                ('visit_preferred_time', models.CharField(blank=True, choices=[('morning', '오전 (09:00 ~ 12:00)'), ('afternoon', '오후 (13:00 ~ 18:00)'), ('evening', '저녁 (19:00 이후)'), ('specific', '특정 시간')], max_length=10, null=True, verbose_name='방문 희망 시간대')),
                ('specific_visit_time', models.TimeField(blank=True, null=True, verbose_name='특정 방문 시간')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
                'db_table': 'customer',
            },
        ),
    ]
