# Generated by Django 5.1.5 on 2025-04-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키')),
                ('address', models.TextField(max_length=100, verbose_name='주소')),
                ('housing_type', models.CharField(max_length=40, verbose_name='주거 형태')),
                ('writer', models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager', verbose_name='작성 담당자')),
            ],
            options={
                'verbose_name': '시공',
                'verbose_name_plural': '시공',
                'db_table': 'construction',
            },
        ),
        migrations.CreateModel(
            name='ConstItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키')),
                ('item_type', models.CharField(choices=[('innerCurtain', '속 커튼'), ('outerCurtain', '겉 커튼'), ('blind', '블라인드'), ('etc', '기타')], max_length=20, verbose_name='품목')),
                ('item_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='아이템 이름')),
                ('item_detail', models.TextField(blank=True, null=True, verbose_name='아이템 설명')),
                ('const_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='construction.construction')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='construction.constitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='constitem',
            index=models.Index(fields=['const_id', 'item_type'], name='constructio_const_i_1a101d_idx'),
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['item_id'], name='constructio_item_id_96566a_idx'),
        ),
    ]
