# Generated by Django 5.1.5 on 2025-04-27 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitem',
            name='const_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='construction.construction', verbose_name='시공'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='construction.constitem', verbose_name='품목 이미지'),
        ),
    ]
