# Generated by Django 5.1.5 on 2025-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='로그인 ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='유저전자메일')),
                ('password', models.CharField(max_length=100, verbose_name='유저PW')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='전화번호')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자',
                'db_table': 'app_manager',
                'unique_together': {('username', 'phone')},
            },
        ),
    ]
